service: movie-metadata-service

app: movie-search-engine
org: igorkorchagin8

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    OMDB_BASE_URL: http://www.omdbapi.com
    OMDB_ACCESS_TOKEN: 68fd98ab
plugins:
  - serverless-plugin-include-dependencies
package:
  exclude:
    - "*"
    - "*/**"
    - "!dist/**"
    - "!movies/**"
    - "!node_modules/**"
functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /api/movies/{id}
          method: get
      - http:
          path: /api/movies
          method: get
